<!DOCTYPE html>
<meta charset="utf-8">
<!-- 
    Welcome
    ê¹€ì§€í˜„ðŸ‡°ðŸ‡·
    1994ë…„ 2ì›” 11ì¼ íƒ„ìƒ
 -->
<html>
    <head>
        <title>Welcome</title>
    </head>
    <body>
        <b>ê¹€ì§€í˜„</b><br>
        <strong>strong text</strong><br>
        <i>italic text</i><br>
        <em>emphasized text</em><br>
        <mark>mark text</mark><br>
        <small>small text</small><br>
        <del>deleted text</del><br>
        <ins>inserted text</ins><br>
        This is <sup>superscript text</sup><br>
        This is <sub>subscript text</sub>
        <h1>Unordered List</h1>
        <ul type="square">
        <li>Coffee</li>
        <li>Tea</li>
        <li>Milk</li>
        </ul>  
    </body>
</html>
